IEproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from ticketing import views
urlpatterns = [
    path('', views.home_page , name='home'),
    path('admin/', admin.site.urls),
    path('ticketing/', include('ticketing.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/details/', views.profile_details, name='profile_details'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('payment/list/', views.payment_list, name='payment_list'),
    path('payment/create/', views.payment_create, name='payment_create'),
]

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # important fields that are stored in User model:
    #  first_name, last_name, email, date_joined

    mobile = models.CharField(max_length=11, blank=True)

    MALE = 1
    FEMALE = 2
    GENDER_CHOICES = ((MALE, 'Male'), (FEMALE, 'Female'))
    gender = models.IntegerField(choices=GENDER_CHOICES, null=True, blank=True)

    birth_date = models.DateField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(upload_to='users/profile_images/',
                                      default='users/profile_images/default_profile_pic.jpg',
                                      null=True, blank=True)

    # fields related to tickets
    balance = models.IntegerField(default=0)

    def __str__(self):
        return self.user.get_full_name()

    def get_balance_display(self):
        return self.balance

    # behaviors
    def deposit(self, amount):
        self.balance += amount
        self.save()

    def spend(self, amount):
        if self.balance < amount:
            return False
        self.balance -= amount
        self.save()
        return True


class Payment(models.Model):
    profile = models.ForeignKey('Profile', on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()
    transaction_time = models.DateTimeField(auto_now_add=True)
    transaction_code = models.CharField(max_length=30)

    def __str__(self):
        return self.profile.__str__() + " (" + self.transaction_code + ")"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.core.exceptions import ValidationError

from accounts.models import Payment, Profile


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['amount', 'transaction_code']

    def clean_transaction_code(self):
        code = self.cleaned_data.get('transaction_code')
        try:
            # should be in format: bank-<amount>-<TOKEN>#
            assert code.startswith('bank-')
            assert code.endswith('#')
            int(code.split('-')[1])
        except:
            raise ValidationError('Receipt is not valid')
        return code


    def clean(self):
        super().clean()
        code = self.cleaned_data.get('transaction_code')
        amount = self.cleaned_data.get('amount')
        if code and amount:
            if int(code.split('-')[1]) != amount:
                raise ValidationError('Receipt and deposit value do not match')


class MyUserForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields = ['first_name', 'last_name', 'email']
    password = None


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['mobile', 'gender', 'address', 'profile_image']

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

# Create your views here.
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from accounts.forms import MyUserForm, ProfileForm, PaymentForm
from accounts.models import Payment, Profile


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            profile = Profile(user=user)
            profile.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    next_url = request.GET.get('next')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        # if such user exists
        if user is not None:
            # Successful login
            login(request, user)
            redirect_url = next_url if next_url else reverse('ticketing:showtime_list')
            return HttpResponseRedirect(redirect_url)
        else:
            # undefined user or wrong password
            context = {
                'username': username,
                'error': 'there is no user with this name!'
            }
    else:
        context = {}
    return render(request, 'accounts/login.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:login'))

@login_required
def profile_details(request):
    profile = request.user.profile
    context = {
        'profile': profile
    }
    return render(request, 'accounts/profile_details.html', context)

@login_required
def payment_list(request):
    payments = Payment.objects.filter(profile=request.user.profile).order_by('-transaction_time')
    context = {
        'payments': payments
    }
    return render(request, 'accounts/payment_list.html', context)


@login_required
def payment_create(request):
    if request.method == 'POST':
        payment_form = PaymentForm(request.POST)
        if payment_form.is_valid():
            payment = payment_form.save(commit=False)
            payment.profile = request.user.profile
            payment.save()
            request.user.profile.deposit(payment.amount)
            return HttpResponseRedirect(reverse('accounts:payment_list'))
    else:
        payment_form = PaymentForm()
    context = {
        'payment_form': payment_form
    }
    return render(request, 'accounts/payment_create.html', context)

@login_required
def profile_edit(request):
    if request.method == 'POST':
        user_form = MyUserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, files=request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('accounts:profile_details'))
    else:
        user_form = MyUserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }
    return render(request, 'accounts/profile_edit.html', context)

accounts/templates/accounts/base_accounts.html
{% extends "ticketing/base_page.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static "accounts/css/accounts.css" %}">
{% endblock %}

accounts/templates/accounts/login.html
{% extends "accounts/base_accounts.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-user"></i>
{% endblock %}

{% block main_content %}
    <form action="" method="post" class="login-form col-lg-4 offset-lg-4 col-md-6 offset-md-3" style="font-size: 1.1rem;">
        {% csrf_token %}
        {% if error %}
        <div class="alert alert-danger col-md-10 offset-md-1">
            {{ error }}
        </div>
        {% endif %}
        <div class="form-group row">
            <label class="col-1">Username:</label>
            <input class="col-12 form-control" type="text" name="username" value="{{ username }}" />
        </div>
        <div class="form-group row">
            <label class="col-1">Password:</label>
            <input class="col-12 form-control" type="password" name="password" />
        </div>
        <div class="form-group row justify-content-center">
            <div class="col-4">
                <button type="submit" class="btn btn-success w-100">
                    Login
                </button>
            </div>
        </div>
        <p class="col-md-8 offset-md-3">Don't have an account?<a href="{% url "accounts:signup" %}" style="color:cornflowerblue">Signup</a> </p>
    </form>
{% endblock %}

accounts/templates/accounts/payment_create.html
{% extends "accounts/base_accounts.html" %}
{% load static %}

{% block title %}
    New Payment
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-plus"></i>
{% endblock %}

{% block main_content %}
    <form action="" method="post" class="form py-2 col-lg-4 offset-lg-4 col-md-6 offset-md-3" style="font-size: 1.15rem;">
    <h5 class="my-2">New Payment</h5>
        {% csrf_token %}
        <table class="my-3 ml-4">
        {{ payment_form.as_table }}
        </table>
        <button type="submit" class="btn btn-success btn-md col-lg-4 offset-lg-4 col-md-5 offset-md-3">
            Submit
        </button>
    </form>
{% endblock %}

accounts/templates/accounts/payment_list.html
{% extends "accounts/base_accounts.html" %}
{% load static %}

{% block title %}
    MyPayment
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-receipt"></i>
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col mt-1 col-md-6 offset-md-1">
            <a href="{% url "accounts:payment_create" %}" class="btn btn-success btn-sm">
                <i class="fas fa-plus"></i>
                New Payment
            </a>
        </div>
        <div class="col py-3 col-md-10 offset-md-1">
            {% if payments %}
                <ul class="item-list">
                    {% for payment in payments %}
                        <li>
                            <span class="ml-4">
                                <span class="text-muted ml-1">
                                    Amount:
                                </span>
                                {{ payment.amount }}
                                T
                            </span>
                            <span class="ml-4">
                                <span class="text-muted ml-1">
                                    TransactionTime:
                                </span>
                                {{ payment.transaction_time|date:"Y/n/j - H:i" }}
                            </span>
                            <span class="ml-4">
                                <span class="text-muted ml-1">
                                    TransactionCode:
                                </span>
                                {{ payment.transaction_code }}
                            </span>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="alert alert-danger">
                    Unavailable
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile_details.html
{% extends "accounts/base_accounts.html" %}
{% load static %}

{% block title %}{{ profile }}{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-user"></i>
{% endblock %}

{% block main_content %}
    <div class="row py-3">
        <div class="col col-md-6 offset-md-3 text-center">
            {% if profile.profile_image %}
                    <img class="profile-image" src="{{ profile.profile_image.url }}" alt="{{ profile }}">
            {% else %}
                    <img class="profile-image" src="{% static 'admin/img/gis/default_profile_pic.jpg' %}" alt="{{ profile }} ">
            {% endif %}
                <div class="profile-buttons mt-4">
                    <a class="btn btn-secondary" href="{% url "accounts:profile_edit" %}">
                        <i class="fas fa-edit"></i>
                        Edit
                    </a>
                </div>
        </div>
    </div>
    <div class="row py-5">
        <div class="col-10 item-details col-md-10 offset-md-1">
            <h4>Profile</h4>
            <div class="row px-3">
                <div class="col-4">
                    <small class="text-muted">
                        <i class="far fa-user"></i>
                        Username:
                    </small>
                </div>
                <div class="col-8">
                    {{ user.username }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="far fa-address-card"></i>
                        FullName:
                    </small>
                </div>
                <div class="col-8">
                    {{ profile.user.get_full_name }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="fas fa-birthday-cake"></i>
                        Birth date:
                    </small>
                </div>
                <div class="col-8">
                    {{ profile.birth_date|date:"Y/n/j" }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="fas fa-mobile-alt"></i>
                        Mobile:
                    </small>
                </div>
                <div class="col-8">
                    {{ profile.mobile }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="fas fa-coins"></i>
                        Balance:
                    </small>
                </div>
                <div class="col-4">
                    {{ profile.get_balance_display }}
                </div>
                <div class="col-4 text-left">
                    <a class="btn btn-xs btn-success my-1" href="{% url "accounts:payment_create" %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="fas fa-home"></i>
                        Address:
                    </small>
                </div>
                <div class="col-8 item-text-box" style="font-size: 0.9rem">
                    {{ profile.address }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends "accounts/base_accounts.html" %}
{% load static %}

{% block title %}
    Profile Edit
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-edit"></i>
{% endblock %}

{% block main_content %}
    <form action="" method="post" enctype="multipart/form-data">
        <div class="row py-3">
            <div class="col col-md-6 offset-md-3 pr-0 text-center">
                {% if user.profile.profile_image %}
                    <img class="profile-image" src="{{ user.profile.profile_image.url }}" alt="{{ user.profile }}">
                {% endif %}
                <br>
                <button type="button" class="btn btn-warning btn-md mt-4"
                        data-toggle="modal" data-target="#profile-image-modal">
                    <i class="fas fa-image"></i>
                </button>
                <div class="modal fade" id="profile-image-modal">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-body">
                            {{ profile_form.profile_image }}
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                </div>
            </div>
        </div>
        {% csrf_token %}
        <div class="row py-5">
            <div class="col-10 item-details col-md-10 offset-md-1 profile-items">
                <h5>Profile Edit</h5>
                <div class="row px-3">
                    <div class="col-2">
                        <small class="text-muted">
                            <i class="far fa-user"></i>
                            Username:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ user.username }}
                    </div>
                    <div class="col-2 pl-0">
                        <small class="text-muted">
                            <i class="far fa-clock"></i>
                            Gender:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ profile_form.gender }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-2">
                        <small class="text-muted">
                            <i class="far fa-address-card"></i>
                            FirstName:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ user_form.first_name }}
                    </div>
                    <div class="col-2 pl-0">
                        <small class="text-muted">
                            <i class="far fa-address-card"></i>
                            LastName:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ user_form.last_name }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-2">
                        <small class="text-muted">
                            <i class="far fa-envelope-open"></i>
                            Email:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ user_form.email }}
                    </div>
                    <div class="col-2 pl-0">
                        <small class="text-muted">
                            <i class="fas fa-mobile-alt"></i>
                            Mobile:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ profile_form.mobile }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-2">
                        <small class="text-muted">
                            <i class="fas fa-home"></i>
                            Address:
                        </small>
                    </div>
                    <div class="col-10 item-text-box">
                        {{ profile_form.address }}
                    </div>
                    <div class="w-300 my-2"></div>
                    <button type="submit" class="btn btn-primary btn-sm">
                        Save
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/base_accounts.html" %}
{% load static %}

{% block title %}Signup{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-user"></i>
{% endblock %}

{% block main_content %}
    <form action="" method="post" class="login-form col-lg-4 offset-lg-4 col-md-6 offset-md-3" style="font-size: 1.15rem;">
        {% csrf_token %}
        {% if error %}
        <div class="alert alert-danger col-md-10 offset-md-1">
            {{ error }}
        </div>
        {% endif %}
        <section class="row row-lg-4 offset-lg-1 row-md-6 offset-md-1">
        {% for field in form %}
              <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                {% if field.help_text %}
                    <br>
                  <small style="color: grey;font-size: 0.8em" >{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
              </p>
        {% endfor %}
        </section>
        <br>
        <div class="form-group row justify-content-center">
            <div class="col-4">
                <button type="submit" class="btn btn-sm btn-success w-100">
                    Signup
                </button>
            </div>
        </div>
    <p class="col-md-10 offset-md-2">have an account already? <a href="{% url "accounts:login" %}" style="color:cornflowerblue">Login</a> </p>
    </form>
{% endblock %}