IEproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from ticketing import views
urlpatterns = [
    path('', views.home_page , name='home'),
    path('admin/', admin.site.urls),
    path('ticketing/', include('ticketing.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/details/', views.profile_details, name='profile_details'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('payment/list/', views.payment_list, name='payment_list'),
    path('payment/create/', views.payment_create, name='payment_create'),
]

ticketing/urls.py
from django.urls import path

from . import views

app_name = 'ticketing'
urlpatterns = [
    path('movie/list/', views.movie_list, name='movie_list'),
    path('movie/details/<int:movie_id>/', views.movie_details, name='movie_details'),
    path('cinema/list/', views.cinema_list, name='cinema_list'),
    path('cinema/details/<int:cinema_id>/', views.cinema_details, name='cinema_details'),
    path('showtime/list/', views.showtime_list, name='showtime_list'),
    path('showtime/details/<int:showtime_id>/', views.showtime_details, name='showtime_details'),
    path('ticket/list/', views.ticket_list, name='ticket_list'),
    path('ticket/details/<int:ticket_id>/', views.ticket_details, name='ticket_details'),
]

ticketing/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    """
    Represents a movie
    """
    name = models.CharField(max_length=100)
    director = models.CharField(max_length=50)
    year = models.IntegerField()
    length = models.IntegerField()
    description = models.TextField()
    poster = models.ImageField(upload_to='movie_posters/')

    def __str__(self):
        return self.name


class Cinema(models.Model):
    """
    Represents a cinema (movie theater)
    """
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    capacity = models.IntegerField()
    phone = models.CharField(max_length=30, blank=True)
    address = models.TextField()
    image = models.ImageField(upload_to='cinema_images/', null=True)

    def __str__(self):
        return self.name


class ShowTime(models.Model):
    """
    Represents a movie show in a cinema at a specific time
    """
    movie = models.ForeignKey('Movie', on_delete=models.PROTECT)
    cinema = models.ForeignKey('Cinema', on_delete=models.PROTECT)

    start_time = models.DateTimeField()
    price = models.IntegerField()
    salable_seats = models.IntegerField()
    free_seats = models.IntegerField()

    SALE_NOT_STARTED = 1
    SALE_OPEN = 2
    TICKETS_SOLD = 3
    SALE_CLOSED = 4
    MOVIE_PLAYED = 5
    SHOW_CANCELED = 6
    status_choices = (
        (SALE_NOT_STARTED, 'Sale not started'),
        (SALE_OPEN, 'Sale is Open'),
        (TICKETS_SOLD, 'Tickets sold'),
        (SALE_CLOSED, 'Sale Closed'),
        (MOVIE_PLAYED, 'Movie played'),
        (SHOW_CANCELED, 'Show canceled'),
    )
    status = models.IntegerField(choices=status_choices, default=SALE_NOT_STARTED)

    def get_price_display(self):
        return '{}'.format(self.price)

    def is_full(self):
        """
        Returns True if all seats are sold
        """
        return self.free_seats == 0

    def open_sale(self):
        """
        Opens ticket sale
        If sale was opened before, raises an exception
        """
        if self.status == ShowTime.SALE_NOT_STARTED:
            self.status = ShowTime.SALE_OPEN
            self.save()
        else:
            raise Exception('Sale has been started before')

    def close_sale(self):
        """
        Closes ticket sale
        If sale is not open, raises an exception
        """
        if self.status == ShowTime.SALE_OPEN:
            self.status = ShowTime.SALE_CLOSED
            self.save()
        else:
            raise Exception('Sale is not open')

    def expire_showtime(self, is_canceled=False):
        """
        Expires showtime and updates the status
        :param is_canceled: A boolean indicating whether the show is canceled or not, default is False
        """
        if self.status not in (ShowTime.MOVIE_PLAYED, ShowTime.SHOW_CANCELED):
            self.status = ShowTime.SHOW_CANCELED if is_canceled else ShowTime.MOVIE_PLAYED
            self.save()
        else:
            raise Exception('Show has been expired before')

    def reserve_seats(self, seat_count):
        """
        Reserves one or more seats for a customer
        :param seat_count: An integer as the number of seats to be reserved
        """
        assert isinstance(seat_count, int) and seat_count > 0, 'Number of seats should be a positive integer'
        assert self.status == ShowTime.SALE_OPEN, 'Sale is not open'
        assert self.free_seats >= seat_count, 'Not enough free seats'
        self.free_seats -= seat_count
        if self.free_seats == 0:
            self.status = ShowTime.TICKETS_SOLD
        self.save()

    def __str__(self):
        return self.movie.name + " (" + self.cinema.name + ")"


class Ticket(models.Model):
    """
    Represents one or more tickets, bought by a user in an order
    """
    showtime = models.ForeignKey('ShowTime', on_delete=models.PROTECT)
    customer = models.ForeignKey('accounts.Profile', on_delete=models.PROTECT)
    seat_count = models.IntegerField()
    order_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.showtime.__str__()

ticketing/forms.py
from django import forms
from ticketing.models import Cinema

class ShowTimeSearchForm(forms.Form):
    PRICE_ANY = '0'
    PRICE_UNDER_10 = '1'
    PRICE_10_TO_15 = '2'
    PRICE_15_TO_20 = '3'
    PRICE_ABOVE_20 = '4'
    PRICE_LEVEL_CHOICES = (
        (PRICE_ANY, 'any price'),
        (PRICE_UNDER_10, 'up to 10T'),
        (PRICE_10_TO_15, '10T to 15T'),
        (PRICE_15_TO_20, '15T to 20T'),
        (PRICE_ABOVE_20, 'more than 20T'),
    )

    movie_name = forms.CharField(max_length=100, required=False)
    sale_is_open = forms.BooleanField(required=False)
    movie_length_min = forms.IntegerField(min_value=0, max_value=200, required=False)
    movie_length_max = forms.IntegerField(min_value=0, max_value=200, required=False)
    cinema = forms.ModelChoiceField(required=False, queryset=Cinema.objects.all())
    price_level = forms.ChoiceField(choices=PRICE_LEVEL_CHOICES, required=False)

    def get_price_boundries(self):
        price_level = self.cleaned_data['price_level']
        if price_level == ShowTimeSearchForm.PRICE_UNDER_10:
            return None, 10000
        elif price_level == ShowTimeSearchForm.PRICE_10_TO_15:
            return 10000, 15000
        elif price_level == ShowTimeSearchForm.PRICE_15_TO_20:
            return 15000, 20000
        elif price_level == ShowTimeSearchForm.PRICE_ABOVE_20:
            return 20000, None
        else:
            return None, None

ticketing/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from ticketing.forms import ShowTimeSearchForm
from ticketing.models import Movie, Cinema, ShowTime, Ticket


def home_page(request):
    movies = Movie.objects.order_by('-year').all()[:5]
    cinemas = Cinema.objects.all()
    context = {
        'movies': movies,
        'cinemas': cinemas,
    }
    return render(request, 'ticketing/homePage.html', context)


def movie_list(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies
    }
    return render(request, 'ticketing/movie_list.html', context)


def cinema_list(request):
    cinemas = Cinema.objects.all()
    context = {
        'cinemas': cinemas
    }
    return render(request, 'ticketing/cinema_list.html', context)


def movie_details(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    context = {
        'movie': movie
    }
    return render(request, 'ticketing/movie_details.html', context)


def cinema_details(request, cinema_id):
    cinema = Cinema.objects.get(pk=cinema_id)
    context = {
        'cinema': cinema
    }
    return render(request, 'ticketing/cinema_details.html', context)


def showtime_list(request):
    showtimes = ShowTime.objects.all()
    search_form = ShowTimeSearchForm(request.GET)
    if search_form.is_valid():
        showtimes = showtimes.filter(movie__name__contains=search_form.cleaned_data['movie_name'])
        if search_form.cleaned_data['sale_is_open']:
            showtimes = showtimes.filter(status=ShowTime.SALE_OPEN)
        if search_form.cleaned_data['movie_length_min'] is not None:
            showtimes = showtimes.filter(movie__length__gte=search_form.cleaned_data['movie_length_min'])
        if search_form.cleaned_data['movie_length_max'] is not None:
            showtimes = showtimes.filter(movie__length__lte=search_form.cleaned_data['movie_length_max'])
        if search_form.cleaned_data['cinema'] is not None:
            showtimes = showtimes.filter(cinema=search_form.cleaned_data['cinema'])
        min_price, max_price = search_form.get_price_boundries()
        if min_price is not None:
            showtimes = showtimes.filter(price__gt=min_price)
        if max_price is not None:
            showtimes = showtimes.filter(price__lte=max_price)
    showtimes = showtimes.order_by('start_time')
    context = {
        'showtimes': showtimes,
        'search_form': search_form
    }
    return render(request, 'ticketing/showtime_list.html', context)

@login_required
def showtime_details(request, showtime_id):
    showtime = ShowTime.objects.get(pk=showtime_id)
    context = {
        'showtime': showtime
    }
    if request.method == 'POST':
        try:
            seat_count = int(request.POST['seat_count'])
            assert showtime.status == showtime.SALE_OPEN, 'not available yet'
            assert showtime.free_seats >= seat_count, 'there are\'nt enough free seats for this showtime'
            price = showtime.price * seat_count
            assert request.user.profile.spend(price), 'your deposit is not enough.'
            showtime.reserve_seats(seat_count)
            ticket = Ticket.objects.create(showtime=showtime, customer=request.user.profile, seat_count=seat_count)
        except Exception as e:
            context['error'] = str(e)
        else:
            return HttpResponseRedirect(reverse('ticketing:ticket_details', kwargs={'ticket_id': ticket.id}))
    return render(request, 'ticketing/showtime_details.html', context)

@login_required
def ticket_list(request):
    tickets = Ticket.objects.filter(customer=request.user.profile).order_by('-order_time')
    context = {
        'tickets': tickets
    }
    return render(request, 'ticketing/ticket_list.html', context)


@login_required
def ticket_details(request, ticket_id):
    ticket = Ticket.objects.get(pk=ticket_id)
    context = {
        'ticket': ticket
    }
    return render(request, 'ticketing/ticket_details.html', context)

ticketing/templates/ticketing/_carousel.html
<div id="demo" class="carousel slide" data-ride="carousel">
      <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
    </ul>

    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="../../../media/home/1.jpeg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="../../../media/home/2.jpeg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="../../../media/home/3.jpeg" alt="First slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#demo" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#demo" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

ticketing/templates/ticketing/_cinema_card.html
<a href="{% url "ticketing:cinema_details" cinema_id=cinema.id %}" class="cinema_card">
<div class="card">
  <img src="../../../media/{{ cinema.image }}" class="card-img-top" alt="{{cinema.name}}">
  <div class="card-body">
    <h5 class="card-title">{{cinema.name}}</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">{{ cinema.city }}</li>
  </ul>
</div>
</a>

ticketing/templates/ticketing/_form_field.html
<label class="col-{{ label_size|default:2 }}" for="{{ field.id_for_label }}">
    {{ field.label }}
</label>
<div class="col-{{ input_size|default:4 }}">
    {{ field }}
    {{ field.errors }}
</div>

ticketing/templates/ticketing/_movie_card.html
<a href="{% url "ticketing:movie_details" movie_id=movie.id %}" class="movie_card">
    <div class="card">
      <img src="../../../media/{{ movie.poster }}" class="card-img-top" alt="{{ movie.name }}">
      <div class="card-body">
        <h5 class="card-title">{{movie.name}}</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Director: {{ movie.director }}</li>
        <li class="list-group-item">Length: {{ movie.length }}</li>
      </ul>
    </div>
</a>

ticketing/templates/ticketing/base_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block extra_headers %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/font-awesome.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/main.css" %}">
    <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />
    <script src="https://unpkg.com/scrollreveal"></script>
    {% block extra_css %}{% endblock %}
</head>
<body>
<div class="container" id="container">

    {% block toolbar %}
    <div class="row align-items-center" id="toolbar">
        <div class="col-6">
            <h4>
                {% block toolbar_title %}{% endblock %}
            </h4>
        </div>
        <div class="col-6 text-right">
            {% block toolbar_buttons %}
                <a class="btn btn-light py-1 px-2" href="{% url "ticketing:movie_list" %}">
                    <i class="fas fa-film"></i>
                    Movies
                </a>
                <a class="btn btn-light py-1 px-2" href="{% url "ticketing:cinema_list" %}">
                    <i class="fas fa-building"></i>
                    Cinemas
                </a>
                <a class="btn btn-success py-1 px-2" href="{% url "ticketing:showtime_list" %}">
                    <i class="fas fa-ticket-alt"></i>
                    Buying Tickets
                </a>

                {% block user_button %}
                {% if user.is_authenticated %}
                    <div class="dropdown">
                        <a class="btn btn-primary dropdown-toggle py-1 px-2" id="user-button" href="#"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right text-left" aria-labelledby="user-button" dir="ltr">
                            <span class="dropdown-item-text">
                                <i class="fas fa-coins"></i>
                                Balance
                                {{ user.profile.balance }}
                                T
                            </span>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url "accounts:profile_details" %}">
                                <i class="far fa-address-card"></i>
                                Profile
                            </a>
                            <a class="dropdown-item" href="{% url "ticketing:ticket_list" %}">
                                <i class="fas fa-ticket-alt"></i>
                                My Tickets
                            </a>
                            <a class="dropdown-item" href="{% url "accounts:payment_list" %}">
                                <i class="fas fa-receipt"></i>
                                MyPayments
                            </a>
                            <a class="dropdown-item" href="{% url "accounts:logout" %}">
                                <i class="fas fa-sign-out-alt"></i>
                                Logout
                            </a>
                        </div>
                    </div>
                {% else %}
                    <a class="btn btn-primary py-1 px-2" href="{% url "accounts:login" %}">
                        <i class="fas fa-sign-in-alt"></i>
                        Login
                    </a>
                    <a class="btn btn-primary py-1 px-2" href="{% url "accounts:signup" %}">
                        <i class="fas fa-arrow-circle-down"></i>
                        Signup
                    </a>
                {% endif %}
            {% endblock %}

            {% endblock %}
        </div>
    </div>
    {% endblock %}

    <div class="row align-items-center" id="header">
        <div class="col text-center" style="margin-bottom: 100px">
            <h1>
                <a href={% url 'home' %} id="home_link">Cinema tickets sale system</a>
            </h1>
        </div>
    </div>


    <div id="main_content">{% block main_content %}{% endblock %}</div>

    <div class="row align-content-center" id="footer">
        <div class="col text-center">
            <span>
                follow us on
                <a class="social-media-icon" href="https://facebook.com/#">
                    <i class="fab fa-facebook"></i>
                </a>
                <a class="social-media-icon" href="https://twitter.com/#">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="social-media-icon" href="https://instagram.com/#">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="social-media-icon" href="https://telegram.org/#">
                    <i class="fab fa-telegram-plane"></i>
                </a>
            </span>
        </div>
    </div>
</div>
<script src="{% static "ticketing/js/jquery-3.4.0.min.js" %}"></script>
<script src="{% static "ticketing/js/bootstrap.bundle.js" %}"></script>
<script src="{% static "ticketing/js/font-awesome.js" %}"></script>
<script src="{% static "ticketing/js/main.js" %}"></script>
<!-- Swiper JS -->
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script>
      var swiper = new Swiper(".mySwiper", {
        slidesPerView: 3,
        spaceBetween: 80,
        slidesPerGroup: 3,
        loop: true,
        loopFillGroupWithBlank: true,
        pagination: {
          el: ".swiper-pagination",
          clickable: true,
        },
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev",
        },
      });
    </script>

{% block extra_js %}{% endblock %}
</body>
</html>

ticketing/templates/ticketing/homePage.html
{% extends "ticketing/base_page.html" %}
{% load static %}

{% block title %}

{% endblock %}

{% block extra_css %}

{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col py-3">
        {% include "ticketing/_carousel.html" %}
        </div>
    </div>

    <div class="row" >
        <div class="col py-3">
            <div class="d-flex justify-content-between">
                <h3>Cinemas</h3>
                <a href="{% url "ticketing:cinema_list"%}" id="see_all_link">
                    see all
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                    </svg>
                </a>
            </div>
            <div class="divider"></div>
            <div class="row" style="padding-bottom: 60px" id="homepage_cinemas">
            <div class="swiper mySwiper">
                   <div class="swiper-wrapper">
                      {% if cinemas %}
                                    {% for cinema in cinemas %}
                                        <div class="swiper-slide" id="h_cinema_wrapper">
                                        {% include "ticketing/_cinema_card.html" with cinema=cinema%}
                                        </div>
                                    {% endfor %}
                            {% endif %}
                  </div>
                  <div class="swiper-button-next" style="color: #d80032"></div>
                  <div class="swiper-button-prev" style="color: #d80032"></div>
                  <div class="swiper-pagination"></div>
            </div>
        </div>
{#            <div class="d-flex justify-content-around " id="homepage_cinemas">#}
{#                {% if cinemas %}#}
{#                        {% for cinema in cinemas %}#}
{#                            {% include "ticketing/_cinema_card.html" with cinema=cinema%}#}
{#                        {% endfor %}#}
{#                {% endif %}#}
{#            </div>#}

            <div class="d-flex justify-content-between">
                <h3>Movies</h3>
                <a href="{% url "ticketing:movie_list"%}" id="see_all_link">
                    see all
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                    </svg>
                </a>
            </div>
            <div class="divider"></div>
            <div class="row" id="homepage_Movies">
            <div class="swiper mySwiper">
              <div class="swiper-wrapper">
                  {% if movies %}
                                {% for movie in movies %}
                                    <div class="swiper-slide" id="h_movie_wrapper">
                                    {% include "ticketing/_movie_card.html" with movie=movie%}
                                    </div>
                                {% endfor %}
                        {% endif %}
              </div>
              <div class="swiper-button-next" style="color: #d80032"></div>
              <div class="swiper-button-prev" style="color: #d80032"></div>
              <div class="swiper-pagination"></div>
            </div>
            </div>
{#            <div class="d-flex justify-content-around flex-md-wrap" id="homepage_Movies">#}
{#                {% if movies %}#}
{#                        {% for movie in movies %}#}
{#                            {% include "ticketing/_movie_card.html" with movie=movie%}#}
{#                        {% endfor %}#}
{#                {% endif %}#}
{#            </div>#}
        </div>
    </div>

{#    <div class="row">#}
{#        <div class="swiper mySwiper">#}
{#      <div class="swiper-wrapper">#}
{#          {% if cinemas %}#}
{#                        {% for cinema in cinemas %}#}
{#                            <div class="swiper-slide">#}
{#                            {% include "ticketing/_cinema_card.html" with cinema=cinema%}#}
{#                            </div>#}
{#                        {% endfor %}#}
{#                {% endif %}#}
{#      </div>#}
{#      <div class="swiper-button-next"></div>#}
{#      <div class="swiper-button-prev"></div>#}
{#      <div class="swiper-pagination"></div>#}
{#    </div>#}
{#    </div>#}
{% endblock %}
{% block extra_js %}
        <script>
        ScrollReveal().reveal('.swiper', {
        delay: 1000,
        useDelay: 'onload',
        reset: true,
        });
        ScrollReveal().reveal('.divider', {
        delay: 500,
        useDelay: 'onload',
        reset: true,
        });
        ScrollReveal().reveal('.row', {
        delay: 500,
        useDelay: 'onload',
        reset: true,
        });
    </script>
{% endblock %}
    <!-- Swiper JS -->
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <!-- Initialize Swiper -->
    <script>
      var swiper = new Swiper(".mySwiper", {
        slidesPerView: 3,
        spaceBetween: 30,
        slidesPerGroup: 3,
        loop: true,
        loopFillGroupWithBlank: true,
        pagination: {
          el: ".swiper-pagination",
          clickable: true,
        },
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev",
        },
      });
    </script>

ticketing/templates/ticketing/showtime_details.html
{% extends "ticketing/base_page.html" %}
{% load static %}

{% block title %}
    Buying Tickets
    {{ showtime.movie.name }}
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-play-circle"></i>
{% endblock %}

{% block toolbar_buttons %}
    <a class="btn btn-warning py-1 px-2" href="{% url "ticketing:showtime_list" %}">
        <i class="fas fa-list"></i>
        ShowTimes List
    </a>
{% endblock %}

{% block main_content %}
    <div class="row py-3">
        <div class="col col-md-6 offset-md-3 text-center">
            <img class="item-image" src="{{ showtime.movie.poster.url }}" alt="{{ showtime.movie.name }}">
        </div>
    </div>
    <div class="row py-5" style="font-size:1rem;">
        <div class="col-10 item-details col-md-10 offset-md-1">
        <h5>{{ showtime.movie.name }}
            <span class="small">
                ({{ showtime.start_time|date:"l - H:i" }})
            </span>
        </h5>
            <div class="row px-3">
                <div class="col-2">
                    <small class="text-muted">
                        <i class="fas fa-film"></i>
                        Movie Name:
                    </small>
                </div>
                <div class="col-10">
                    {{ showtime.movie.name }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-2">
                    <small class="text-muted">
                        <i class="fas fa-building"></i>
                        Cinema Name:
                    </small>
                </div>
                <div class="col-8">
                    {{ showtime.cinema.name }}
                </div>
                <div class="col-2 text-left">
                    {% if showtime.status == showtime.SALE_OPEN %}
                        <span class="badge
                            {% if showtime.free_seats < 10 %}
                                badge-danger
                            {% else %}
                                badge-info
                            {% endif %}">
                        {{ showtime.free_seats }}
                        Free Seats
                        </span>
                    {% else %}
                        <span class="badge badge-dark">
                            {{ showtime.get_status_display }}
                        <span>
                    {% endif %}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-2">
                    <small class="text-muted">
                        <i class="far fa-clock"></i>
                        Start Time:
                    </small>
                </div>
                <div class="col-10">
                    {{ showtime.start_time|date:"l Y/n/j - H:i" }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-2">
                    <small class="text-muted">
                        <i class="fas fa-map-marker-alt"></i>
                        Address:
                    </small>
                </div>
                <div class="col-10 item-text-box">
                    {{ showtime.cinema.address }}
                </div>
                {% if showtime.status == showtime.SALE_OPEN %}
                    <div class="w-100 my-1"></div>
                    <div class="col-2">
                        <small class="text-muted">
                            <i class="fas fa-money-bill-wave"></i>
                            Price:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ showtime.price }}
                        T
                    </div>
                    <div class="col-6">
                    <form action="" method="post" class="form-inline">
                        {% csrf_token %}
                        <select name="seat_count" class="form-control form-control-sm ml-2">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                        <button type="submit" class="btn btn-xs btn-success my-1">
                            Buy
                        </button>
                    </form>
                    </div>
                {% endif %}
                {% if error %}
                    <div class="w-100 my-1"></div>
                    <span class="col-12 alert alert-danger align-items-baseline small p-2">
                        <i class="fas fa-exclamation-circle"></i>
                        {{ error }}
                    </span>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}